config/routes.rb
Rails.application.routes.draw do

  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  delete '/profiles/:id', to: 'profiles#destroy', as: :destroy_profile

  # Perfil de usuário
  get '/profiles/:id', to: 'profiles#show', as: :profile

  # Index e resultados de pesquisa de usuário
  get '/profiles', to: 'profiles#index', as: :profiles

  # Rota para criar pedido de amizade
  post '/friendship/:id', to: 'profiles#add_friend', as: :add

  # Pagina Para visualizar os amigos de alguem, e se o :id for seu, permite aceitar pedidos de amizade
  get '/profiles/:id/friends', to: 'profiles#friends', as: :friends

  # Aceita pedidos de amizade
  post '/profiles/:id/friends/accept', to: 'profiles#accept_friendship', as: :accept_friendship
  
  # Desfaz amizade
  delete '/remove_fs/:id', to: 'profiles#destroy_friendship', as: :destroy_friendship

  # Desfaz amizade
  delete '/profiles/:id/cancel_friendship', to: 'profiles#cancel_friendship', as: :cancel_friendship

  # Comentario
  post '/posts/:id/comment', to: 'posts#comment', as: :comment

  # Apagar comentário
  delete '/posts/:id/delete_comment/:comment_id', to: 'posts#delete_comment', as: :delete_comment

  # Like/Deslike
  patch '/posts/:id/like', to: 'posts#like', as: :like

  # Raiz - apenas para redirecionamento
  root to: 'static_pages#root'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_user, only: [:cancel_friendship, :destroy_friendship, :accept_friendship, :friends, :show, :destroy, :add_friend]
    before_action :block_not_adm, only: :destroy
    before_action :block_non_logged

    def block_not_adm
        if user_signed_in?
            redirect_to profile_path(current_user.id)
        else
            redirect_to new_user_session_path
        end
    end
    
    def accept_friendship
        @friend = Friend.find_by(replyer_id: @user.id, asker_id: current_user.id)
        puts @user.id, current_user.id
        @friend.accepted = true
        @friend.save
        redirect_to friends_path(current_user.id)
    end
    
    def cancel_friendship
        @friend = Friend.find_by(asker_id: @user.id, replyer_id: current_user.id)
        @friend2 = Friend.find_by(asker_id: current_user.id, replyer_id: @user.id)
        @friend.destroy
        @friend2.destroy
        redirect_to profile_path(@user.id)
    end

    def destroy_friendship
        @friend = Friend.find_by(asker_id: @user.id, replyer_id: current_user.id)
        @friend2 = Friend.find_by(asker_id: current_user.id, replyer_id: @user.id)
        @friend.destroy
        @friend2.destroy
        redirect_to friends_path(current_user.id)
    end

    def friends
        @friend_asks = Friend.where(asker_id: @user.id, accepted: false)
        @friends = friendships(@user)
    end

    def add_friend
        if Friend.where(asker_id: current_user.id, replyer_id: @user.id).count() == 0
            Friend.create(asker_id: current_user.id, replyer_id: @user.id, accepted: true)
            Friend.create(asker_id: @user.id, replyer_id: current_user.id)
        end
        redirect_to profile_path(@user.id)
    end

    def show
        @posts = Post.where(user_id: @user.id)
        @friends = Friend.where(asker_id: @user.id)
        @is_friend = Friend.where(asker_id: current_user.id, replyer_id: @user.id).count()
    end
    

    def destroy
        @user.destroy
        redirect_to profiles_path
    end

    def index
        @users = if params[:term]
            User.where("name LIKE (?)", "%#{params[:term]}%").paginate(page: params[:page], per_page: 10)
        else
          User.paginate(page: params[:page], per_page: 10)
        end
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
        @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/friends.html.erb
<strong>Amigos de <%= @user.name %>:</strong> <br/>
<% @friends.each do |f| %>
  <%= link_to User.find(f[1]).name, profile_path(f[1]) %> <br/>
  <% if current_user.id == @user.id %><%= link_to "Desfazer Amizade", destroy_friendship_path(f[1]), method: :delete%> <% end %>
<% end %>
<br/>
<% if @user.id == current_user.id %>
<strong>Pedidos de amizade:</strong> <br/>
    <% @friend_asks.each do |f| %>
        <%= f.replyer.name %> <%= link_to "Aceitar", accept_friendship_path(f.replyer_id), method: :post %>
    <% end %>
<br/>
<% end %>

<br/>
<%= link_to "Voltar", profile_path(@user.id)%>
<br/><br/><br/>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <% if current_user.adm == true %>
        <th colspan="2"></th>
      <% else %>
        <th colspan="0"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', profile_path(user.id) %></td>
        <% if current_user.adm == true %>
          <td><%= link_to 'Destroy', destroy_profile_path(user.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if params[:term] %>
  <%= link_to "Back", profiles_path%>
<% end %>
<%= will_paginate @users %>

<br>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @user.avatar  if @user.avatar.attached? %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<%= link_to "Amigos", friends_path(@user.id)%>
<% if @user.id == current_user.id%>
  <%= link_to 'Edit', edit_user_registration_path(@user) %> 
<% else %>
  <% if @is_friend == 0 %>
    <%= link_to "Adicionar amigo", add_path(@user.id), method: :post%>
  <% else %>
    <%= link_to "Cancelar solicitação", cancel_friendship_path, method: :delete %>
  <% end %>
<% end %>
<br/>
<% if @posts.count != 0 %>

<% @posts.each do |p| %>
  <br/>
  -----------------------------<br/>
  <strong>Criado em: </strong> <%= p.created_at %>
  <br/>
  <strong>Conteúdo: </strong> <%= p.content %>
  <% if p.image.attached? %>
    <strong>Image:</strong>
    <%= image_tag p.image %>
  <% end %>
  <%= link_to "Visualizar", post_path(p.id) %>
  <br/>
  -----------------------------

<% end %>
<% end %>
<br/>

<%= link_to 'Back', profiles_path %>