config/routes.rb
Rails.application.routes.draw do

  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  delete '/profiles/:id', to: 'profiles#destroy', as: :destroy_profile

  # Perfil de usuário
  get '/profiles/:id', to: 'profiles#show', as: :profile

  # Index e resultados de pesquisa de usuário
  get '/profiles', to: 'profiles#index', as: :profiles

  # Rota para criar pedido de amizade
  post '/friendship/:id', to: 'profiles#add_friend', as: :add

  # Pagina Para visualizar os amigos de alguem, e se o :id for seu, permite aceitar pedidos de amizade
  get '/profiles/:id/friends', to: 'profiles#friends', as: :friends

  # Aceita pedidos de amizade
  post '/profiles/:id/friends/accept', to: 'profiles#accept_friendship', as: :accept_friendship
  
  # Desfaz amizade
  delete '/remove_fs/:id', to: 'profiles#destroy_friendship', as: :destroy_friendship

  # Desfaz amizade
  delete '/profiles/:id/cancel_friendship', to: 'profiles#cancel_friendship', as: :cancel_friendship

  # Comentario
  post '/posts/:id/comment', to: 'posts#comment', as: :comment

  # Apagar comentário
  delete '/posts/:id/delete_comment/:comment_id', to: 'posts#delete_comment', as: :delete_comment

  # Like/Deslike
  patch '/posts/:id/like', to: 'posts#like', as: :like

  # Raiz - apenas para redirecionamento
  root to: 'static_pages#root'
end

app/models/post.rb
class Post < ApplicationRecord
    # Dependências
    has_one_attached :image
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy
    
    # Validações
    validate :image_size
    validates :content, presence: true, length: {in: 2..140}

    def image_size
        if image.attached? and image.blob.byte_size > 1000000
            image.purge
            errors.add(:icon,  "Imagem muito grande")
        end
    end
end

app/controllers/posts_controller.rb
include PostsHelper
class PostsController < ApplicationController
  before_action :set_post, only: [:like, :delete_comment, :comment, :show, :edit, :update, :destroy]
  before_action :protect_edition, only: [:edit, :update]
  before_action :protect_destroy, only: :destroy
  before_action :protect_destroy_comment, only: :delete_comment
  before_action :block_non_logged

  # GET /posts
  # GET /posts.json
  def index
    @ids_aux = friendships(current_user)
    @ids = []
    @ids_aux.each do |t|
      @ids.push(t[1])
    end
    puts @ids
    @posts = Post.where(user_id: @ids).order(created_at: :desc).paginate(page: params[:page], per_page: 9)
  end

  def like
    @like = Like.find_by(user_id: current_user.id, post_id: @post.id)
    if @like
      @like.destroy
    else
      @like = Like.create(user_id: current_user.id, post_id: @post.id)
    end
    redirect_to post_path(@post.id)
  end


  def comment
    @comment = Comment.new(content: params[:comment][:content])
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_path(@post.id)
  end

  def delete_comment

    @comment = Comment.find(params[:comment_id])
    if @comment.user_id == current_user.id or current_user.adm == false
      @comment.destroy
    end
    redirect_to post_path(@post.id)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @like = Like.find_by(user_id: current_user.id, post_id: @post.id)
    @likes = Like.where(post_id: @post.id).count()
    @comments = Comment.where(post_id: @post.id).paginate(page: params[:page], per_page: 6)
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :image, :user_id)
    end

    def comment_params
      params.permit(:content, :post_id, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def protect_edition
        if @post.user_id != current_user.id
            redirect_to profiles_path(current_user.id)
        end
    end

    def protect_destroy
        if current_user.adm == true and @post.user_id == current_user.id
        else
            redirect_to profiles_path(current_user.id)
        end
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div><%= form.label :image %> <%= form.file_field :image %></div>
  <br/>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Content</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td> <%= post.user.name %> </td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <% if post.image.attached? %>
          <td><%= image_tag post.image %></td>
        <% end %>
        <% if current_user.id == post.user_id %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>
        <% if current_user.id == post.user_id or current_user.adm == true%>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @posts %>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Postagem de: <%= link_to @post.user.name, profile_path(@post.user.id)%><br/>
  <strong>Content:</strong>
  <%= @post.content %><br/>
  
  <% if @post.image.attached? %>
    <strong>Image:</strong>
    <%= image_tag @post.image %><br/>
  <% end %>
  Contagem de likes:
  <%= @likes %> <br/> <% if @like %>
    <%= link_to "Deslike", like_path(@post.id), method: :patch%>
  <% else %>
    <%= link_to "Like", like_path(@post.id), method: :patch%>
  <% end %>

</p>
<% @comments.each do |c|%>
  <strong><%= link_to c.user.name, profile_path(c.user.id) %></strong> <%= c.content %>
  <% if current_user.id == c.user_id%>
    <%= link_to "Apagar comentário", delete_comment_path(@post.id, c.id), method: :delete%> 
  <% end %> <br/> 
<% end %>
<%= will_paginate @comments %>
<%= form_for( @comment, url: comment_path, method: :post) do |form| %>
        <%= form.text_field :content %>
      <%= form.submit "Comentar"%>
<% end %>
<% if current_user.id == @post.user_id%>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>