config/routes.rb
Rails.application.routes.draw do

  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  delete '/profiles/:id', to: 'profiles#destroy', as: :destroy_profile

  # Perfil de usuário
  get '/profiles/:id', to: 'profiles#show', as: :profile

  # Index e resultados de pesquisa de usuário
  get '/profiles', to: 'profiles#index', as: :profiles

  # Rota para criar pedido de amizade
  post '/friendship/:id', to: 'profiles#add_friend', as: :add

  # Pagina Para visualizar os amigos de alguem, e se o :id for seu, permite aceitar pedidos de amizade
  get '/profiles/:id/friends', to: 'profiles#friends', as: :friends

  # Aceita pedidos de amizade
  post '/profiles/:id/friends/accept', to: 'profiles#accept_friendship', as: :accept_friendship
  
  # Desfaz amizade
  delete '/remove_fs/:id', to: 'profiles#destroy_friendship', as: :destroy_friendship

  # Desfaz amizade
  delete '/profiles/:id/cancel_friendship', to: 'profiles#cancel_friendship', as: :cancel_friendship

  # Comentario
  post '/posts/:id/comment', to: 'posts#comment', as: :comment

  # Apagar comentário
  delete '/posts/:id/delete_comment/:comment_id', to: 'posts#delete_comment', as: :delete_comment

  # Like/Deslike
  patch '/posts/:id/like', to: 'posts#like', as: :like

  # Raiz - apenas para redirecionamento
  root to: 'static_pages#root'
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Demo App", root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Posts', '#' %></li>
                <% if current_user %>
                    <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<% if user_signed_in? %>
  Voce está conectado como <%= link_to current_user.name, profile_path(current_user.id) %>, <%= link_to "desconectar", destroy_user_session_path, method: :delete  %>
  <%= form_tag(profiles_path, method: :get) do %>  
    <%= text_field_tag :term, params[:term], :placeholder => "Procure por nomes..",:class => "busca-input" %>
    <%= submit_tag 'Encontrar', name: nil,:class => "busca-submit" %>
  <% end %>
  <%= link_to "Feed", posts_path%> <%= link_to "Usuários", profiles_path%>
  <%= link_to 'New Post', new_post_path %>
<% end %>
  <head>
    <title>Conectados</title>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <br/>
  <body>
    <%= yield %>
  </body>
</html>